import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Nav from '@/components/Nav'
import Sheet from '@/components/Sheet'
import Hotkeys from '@/components/Hotkeys'

import styles from '@styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  Hotkeys()
  return (
    <>
      <Head>
        <title>Caption Studio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header>
        <Nav />
      </Header>
      <Sheet />
    </>
  )
}
